import {
  BceidIdentityProvider,
  DigitalCredentialsIdentityProvider,
  GithubIdentityProvider,
  IdirIdentityProvider,
  OriginalSSOUser,
  VCPresentedAttributes,
} from '@/types';

export type MockOriginalSSOUser = OriginalSSOUser<unknown, object | undefined>;

export const mockUser: MockOriginalSSOUser = {
  exp: 0,
  iat: 0,
  auth_time: 0,
  jti: '',
  iss: '',
  aud: '',
  sub: '',
  typ: '',
  azp: '',
  nonce: '',
  session_state: '',
  sid: '',
  identity_provider: '',
  email_verified: false,
  preferred_username: '',
  client_roles: ['role1', 'role2', 'role3'],
};

export const mockIdirUser: OriginalSSOUser<IdirIdentityProvider, undefined> = {
  exp: 0,
  iat: 0,
  auth_time: 0,
  jti: '',
  iss: '',
  aud: '',
  sub: '',
  typ: '',
  azp: '',
  nonce: '',
  session_state: '',
  sid: '',
  identity_provider: 'idir',
  email_verified: false,
  preferred_username: '',
  client_roles: ['role1', 'role2', 'role3'],
  idir_user_guid: 'idir-guid',
  idir_username: 'idir-username',
  name: 'John Doe',
  display_name: 'John Doe',
  given_name: 'John',
  family_name: 'Doe',
  email: 'john.doe@example.com',
};

export const mockBceidUser: OriginalSSOUser<BceidIdentityProvider, undefined> = {
  exp: 0,
  iat: 0,
  auth_time: 0,
  jti: '',
  iss: '',
  aud: '',
  sub: '',
  typ: '',
  azp: '',
  nonce: '',
  session_state: '',
  sid: '',
  identity_provider: 'bceidbusiness',
  email_verified: false,
  preferred_username: '',
  client_roles: ['role1', 'role2', 'role3'],
  bceid_user_guid: 'bceid-guid',
  bceid_username: 'bceid-username',
  bceid_business_name: 'Doe Inc.',
  name: 'Jane Doe',
  display_name: 'Jane Doe',
  given_name: 'Jane',
  family_name: 'Doe',
  email: 'jane.doe@example.com',
};

export const mockGithubUser: OriginalSSOUser<GithubIdentityProvider, undefined> = {
  exp: 0,
  iat: 0,
  auth_time: 0,
  jti: '',
  iss: '',
  aud: '',
  sub: '',
  typ: '',
  azp: '',
  nonce: '',
  session_state: '',
  sid: '',
  identity_provider: 'githubbcgov',
  email_verified: false,
  preferred_username: '',
  client_roles: ['role1', 'role2', 'role3'],
  github_id: 'github-id',
  github_username: 'github-username',
  orgs: 'bcgov',
  org_verified: 'true',
  name: 'Github User',
  display_name: 'Github User',
  given_name: 'Github',
  family_name: 'User',
  email: 'github.user@example.com',
};

export type MockDCAttributes = {
  email: string;
};

export const mockDigitalCredentialsUser: OriginalSSOUser<
  DigitalCredentialsIdentityProvider,
  MockDCAttributes
> = {
  exp: 0,
  iat: 0,
  auth_time: 0,
  jti: '',
  iss: '',
  aud: '',
  sub: '',
  typ: '',
  azp: '',
  nonce: '',
  session_state: '',
  sid: '',
  identity_provider: 'digitalcredential',
  email_verified: false,
  preferred_username: 'dc-user@example.com',
  pres_req_conf_id: 'conf-id',
  vc_presented_attributes: JSON.stringify({
    email: 'dc.user@example.com',
  }) as VCPresentedAttributes<MockDCAttributes>,
};
